### ISSUE TITLE
Could we get the source code for this?

### ISSUE THREAD

**Issue by protosam** [ephtracy/ephtracy.github.io#108]
@darkfall @ephtracy @cvan @u32i64 

I created issue #93  prior and it was derailed by off-topic conversation overall. 

Someone mentioned they would like to compile this application for linux and I personally would like to audit anything I'm running on my devices to know it's safe for consumption.

I'm not asking for it to be open-sourced, I'm fine with some form of restrictive licensing. I would just like to ask for you guys to weigh in on if you would be up for releasing the source for us to peer-review, audit, and help patch.

Thanks,

Sam

**Comment by ephtracy** [comment]
Sorry, but no. Some reasons why the project is not open-sourced yet:

1. The project is also used as my personal research platform, so it contains codes for unpublished features and from other private projects.

2. Freeware is not free to make; open-sourcing is not simply throwing codes online as well. Everything comes at a cost. Unfortunately I do not have enough resources for that at the moment. Timing is important too.

3. I prefer working on my hobby projects at my own pace.

4. The project is hosted in the private repositories which are paid monthly to github.

**Comment by protosam** [comment]
Point 1 is fine enough for me @ephtracy . I wasn't asking for this to be open source, just for the source to be available. You can license it is a ton of different ways with various restrictions.

Despite that we don't agree on your stances, I really just wanted to hear from you and I appreciate you reaching out.

**Comment by X3msnake** [comment]
what about licensing? are you willing to license the source?

**Comment by erlend-sh** [comment]
Fully support your stance on this @ephtracy. Here's two great articles from open source maintainers that have run into a lot of the problems that you're choosing to keep at bay:

https://mikemcquaid.com/2018/03/19/open-source-maintainers-owe-you-nothing/
https://hueniverse.com/a-new-social-contract-for-open-source-86d1fcf3e353

I do think there are some fairly safe steps you could take to gradually move in the direction of a sustainable open source project. For starters, like you've done here, you could add more trustworthy collaborators to the private repo. Allowing for more people to make a volunteer contribution to the project would further distribute the maintenance burden, making you better prepared for an open source release should you ever want to go down that path.

I get my paycheck by working on open source. If you'd like to discuss more about how to do open source without breaking your back I'd be happy to chat at length with you: erlend@discourse.org

**Comment by rubenwardy** [comment]
Making it open source would just make it easier for people to fix porting issues for their own operating systems. For example, I'd love to use this on Linux, but there's no version available for it. You don't need to accept PRs - you can disable that if you wish.

Also, unless you compile out the code the private research code will still be there anyway

**Comment by swedneck** [comment]
I don't see how making the project open source would in any way shape or form make it more expensive, in fact it would save money that is currently spent on private repos and people would be free to make their own bug fixes and improvements.

**Comment by burhop** [comment]
Maybe an API or add-in framework would be good?  This would keep your code private.  For example, I'd love to automate a few tasks like animations, setting voxels and so on.  Having access to the VOX format has already been a big help.

**Comment by jdiperla** [comment]
You can add Shaders and Plugins for this... Look here:
https://ephtracy.github.io/index.html?page=mv_resource There are some
scripts and shaders that allow you to use the command line to perform
custom actions.

**Comment by burhop** [comment]
@jdiperla Thanks, that was actually quite helpful.  I wrote a couple shaders and it worked pretty well.  
 For the scripts, not  so much as the examples were them just replaying key presses on the Mac.  

I didn't see a way to batch commands. For the shaders, you can repeat them by using a command like this:
 `xs -n 5 myshader`
 
I was hoping to see intermediate steps, not just the final output so I'm not quite there.

**Comment by unphased** [comment]
Just a note for folks, the magicavoxel 0.99.4 win64 build works flawlessly under Wine on Ubuntu 18.04. Sure, It is not ideal, but there are no apparent problems whatsoever.

**Comment by Michaelangel007** [comment]
Sad to see another developer make try to pass off excuses 2, 3, and 4 as valid reasons. :-/

Excuse #2. The cost of development is another red herring. You are _already_ hosting the project on git hub.  All you are doing by switching to an open source model is changing the _distribution._

Excuse #3. No one dictates your release schedule since you are the sole author.  The project being open or closed **doesn't** change this.

With that said, Reason #1 is THE reason to keep the project closed source. If you are under contractual agreement(s) then you need to honor them.  However, id software went through the EXACT same problem when they released the source for Quake -- they used an proprietary audio library and had to strip it out of the source.  The solution is to let the community develop drop-in replacements for the libraries.

I work on multiple open source projects.  One is commercial, the others not.  In the commercial open source project we do the same thing.  We conditionally compile the C++ code depending on whether you have licenses to use the closed-source, proprietary libraries. If not, you can use open source library replacements.

There ARE solutions to every "reason".   If the author doesn't have the time or motivation for #1 then that is perfectly understood.  However, the community _may_ be willing to chip in and help -- if allowed to.
